FROM ruby:3.0.0

# RUN   apt-get install -y build-base \
RUN   apt-get update && apt-get install -y default-mysql-client \
                       curl \
                       bash \
                       nodejs \
                       tzdata

WORKDIR /app

COPY . ./

RUN gem install bundler:2.0.1 && bundle install

CMD bundle exec rails s -p 3000 -b '0.0.0.0'