FROM ruby:2.7.3-alpine3.13

RUN apk update && \
    apk --no-cache add bash \
                       build-base \
                       curl \
                       mysql-dev \
                       nodejs \
                       tzdata

WORKDIR /app

COPY ./Gemfile* ./

RUN gem install bundler && bundle install

COPY . ./

CMD bundle exec rails s -p 3000 -b '0.0.0.0'