version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      DB_USERNAME: mysql_user
      DB_PASSWORD: mysql_user
      DB_HOSTNAME: mysql
      DATABASE_NAME: sampledb
    ports:
      - "3306:3306"

  rails:
    build:
      context: ./RailsSample
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - mysql