version: '3'

services:
  mysql:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306

  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile.alpine
    volumes:
      - ./rails:/app/
    ports:
      - '3000:3000'
    depends_on:
      - mysql
