version: '3'

services:
  mysql_for_rails4:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - mysql_for_rails4-data:/var/lib/mysql
    ports:
      - 3306:3306

  rails4:
    build:
      context: ./rails
      dockerfile: Dockerfile.alpine
    volumes:
      - ./rails:/app/
    ports:
      - '3000:3000'
    depends_on:
      - mysql_for_rails4

volumes:
  mysql_for_rails4-data:
    driver: local