FROM ruby:2.6-alpine3.15

RUN apk update && \
    apk --no-cache add bash \
                       build-base \
                       curl \
                       mysql-dev \
                       nodejs \
                       tzdata

WORKDIR /app

COPY ./Gemfile* ./

RUN gem install bundler && export MAKE="make --jobs 4" && bundle install
# RUN gem install bundler:1.7.13 && bundle install

COPY . ./

CMD bundle exec rails s -p 3000 -b '0.0.0.0'