FROM ruby:2.7.0-alpine3.11

RUN apk update && \
    apk --no-cache add bash \
                       build-base \
                       curl \
                       mysql-dev \
                       nodejs \
                       tzdata \
                       libffi-dev

WORKDIR /app

COPY ./Gemfile* ./

RUN gem install bundler && bundle config set path 'vendor/bundle' && bundle install
# RUN gem install bundler && bundle install

COPY . ./

CMD bundle exec rails s -p 3000 -b '0.0.0.0'